# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Maîtriser ça ! Apprendre sur la web 3 et les chaînes de blocs"
author:
  name: Serafim Dos Santos
  email: info@maitriser.ca
description: >- # this means to ignore newlines until "baseurl:"
  Maitriser.ca est un site de toile internet offrant des documents informatifs et éducatifs sur les sujets de développement web 2.0 et 3.0 ansi que sur les technologies de chaînes de blocs / blockchain; et ce gratuitement! Les documents source sont généralement disponibles sur GitHub.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.maitriser.ca" # the base hostname & protocol for your site, e.g. http://example.com

social_links:
  twitter: serafdossantos
  github:  SerafDosSantos

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme configuration
minima:
  skin: classic

show_excerpts: true # set to true to show excerpts on the homepage

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
